export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_RESPONSE = 'FETCH_RESPONSE';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SET_CURRENT_MAIL = 'SET_CURRENT_MAIL';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';